### ISSUE TITLE
Pass file extension as param

### ISSUE THREAD

**Issue by ayamflow** [mailmojo/hoganify#4]
Hey!
I've been using hoganify and I have to say it's really nice, no pain to setup, it just works™.

I'd like to be able to specify the extension of the templates, like using `.html` or other (like mustache server-side). Is it possible to pass parameters to a browerify transform via the package.json?
If not possible, would you consider adding html to the supported extensions list ? I know it's more "comestic" but I sometime have to re-use `.html` mustache templates from the server.

Thanks!

**Comment by fdanielsen** [comment]
Hi!

Thanks for your kind words, I'm glad you've found good use of `hoganify` :)

With my 0.2.0 release I added support for custom extensions, and part of it was to allow usage of `.html` if one needed. I do not want that as one of the default extensions since it's such a generic extension.

But it should be perfectly fine to supply the `ext` option through package.json too, with something like this:

``` json
"browserify": {
  "transform": [
    ["hoganify", {"ext": ".html"}]
  ]
}
```

The `ext` option allows a comma separated string of extensions, so if you need to support other extensions than `.html` you could just add it to the value, like: `{"ext": ".html,.hg"}`.

**Comment by ayamflow** [comment]
Damnit, it's even in the docs, how did I miss that !
Thanks a bunch, will try!

**Comment by fdanielsen** [comment]
Hehe, yes, that's where I had to double check before suggesting it. No problem, hope it works for you :) By the way, some really cool animation experiments you've got on your site!

**Comment by ayamflow** [comment]
Thanks :)
Just tested, works like a charm.
